server:
  port: 8770

spring:
  application:
    name: eureka-service-a
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/